env:
  simulator: "vcs"

common_compile_option: &common_compile >-
  -sverilog
  -ntb_opts uvm-1.2

common_sim_option: &common_sim >-
  +UVM_VERBOSITY=UVM_LOW
  +UVM_CONFIG_DB_TRACE

builds:
  build1:
    compile_option:
      - *common_compile
      - -timescale=1ns/10ps
    pre_sim_option:
      - echo "pre_sim_build1"
    sim_option:
      - *common_sim
    post_sim_option:
      - echo "post_sim_build1"

  build2:
    pre_compile_option:
      - echo "pre_compile_build2"
    compile_option:
      - -debug_access+pp
      - *common_compile
    post_compile_option:
      - echo "post_compile_build2"
    sim_option:
      - *common_sim

options:
  vh:
    on_action:
      sim_option:
        - +UVM_VERBOSITY=UVM_FULL

  has_pre_phase:
    with_value_action:
      pre_compile_option:
        - echo "pre_compile_option $has_pre_phase"
      post_compile_option:
        - echo "post_compile_option $has_pre_phase"
      pre_sim_option:
        - echo "pre_sim_option $has_pre_phase"
      post_sim_option:
        - echo "post_sim_option $has_pre_phase"

groups:
  group1:
    build: build1
    args:
      - -vh
      - -repeat 1
    tests:
      test1:
        args:
          - -repeat 10
      test2:
        args:
          - -seed 1

  group2:
    build: build2
    args:
      - -vh
      - -repeat 1
    tests:
      test3:
        args:
          - -repeat 10
    groups:
      - group1